"""add_missing_foreign_keys

Revision ID: 641b83e9a64f
Revises: eb9549daa89a
Create Date: 2025-03-19 16:52:40.215450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '641b83e9a64f'
down_revision: Union[str, None] = 'eb9549daa89a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_cpv_codes', 'cpv_codes', ['cpv_code'], ['code'])
    op.create_foreign_key(None, 'user_keywords', 'keywords', ['keyword'], ['keyword'])
    op.create_foreign_key(None, 'user_tender_types', 'tender_types', ['tender_type'], ['type_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tender_types', type_='foreignkey')
    op.drop_constraint(None, 'user_keywords', type_='foreignkey')
    op.drop_constraint(None, 'user_cpv_codes', type_='foreignkey')
    # ### end Alembic commands ###
