"""Add es_description to cpv_codes table

Revision ID: bad702658d08
Revises: a218ad8f4e0a
Create Date: 2025-03-20 10:36:28.295496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad702658d08'
down_revision: Union[str, None] = 'a218ad8f4e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cpv_codes', sa.Column('es_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cpv_codes', 'es_description')
    # ### end Alembic commands ###
