"""create initial tables

Revision ID: eb9549daa89a
Revises: 
Create Date: 2025-03-19 16:27:04.395919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9549daa89a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpv_codes',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('keywords',
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('keyword')
    )
    op.create_table('tender_summaries',
    sa.Column('id', sa.String(255), nullable=False),
    sa.Column('tender_uri', sa.String(1024), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_summaries_tender_uri'), 'tender_summaries', ['tender_uri'], unique=True)
    op.create_table('tender_types',
    sa.Column('type_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('type_code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('client', 'account_manager')", name='chk_user_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('user_tenders',
    sa.Column('id', sa.String(255), nullable=False),
    sa.Column('user_id', sa.String(255), nullable=False),
    sa.Column('tender_id', sa.String(255), nullable=False),
    sa.Column('tender_uri', sa.String(1024), nullable=False),
    sa.Column('saved_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tender_id', name='uq_user_tender')
    )
    op.create_index(op.f('ix_user_tenders_tender_id'), 'user_tenders', ['tender_id'], unique=False)
    op.create_index(op.f('ix_user_tenders_user_id'), 'user_tenders', ['user_id'], unique=False)
    op.create_table('user_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('min_budget', sa.Float(), nullable=True),
    sa.Column('max_budget', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_criteria_id'), 'user_criteria', ['id'], unique=False)
    op.create_table('user_cpv_codes',
    sa.Column('user_criteria_id', sa.Integer(), nullable=False),
    sa.Column('cpv_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_criteria_id'], ['user_criteria.id'], ),
    sa.PrimaryKeyConstraint('user_criteria_id', 'cpv_code')
    )
    op.create_table('user_keywords',
    sa.Column('user_criteria_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_criteria_id'], ['user_criteria.id'], ),
    sa.PrimaryKeyConstraint('user_criteria_id', 'keyword')
    )
    op.create_table('user_tender_types',
    sa.Column('user_criteria_id', sa.Integer(), nullable=False),
    sa.Column('tender_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_criteria_id'], ['user_criteria.id'], ),
    sa.PrimaryKeyConstraint('user_criteria_id', 'tender_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tender_types')
    op.drop_table('user_keywords')
    op.drop_table('user_cpv_codes')
    op.drop_index(op.f('ix_user_criteria_id'), table_name='user_criteria')
    op.drop_table('user_criteria')
    op.drop_index(op.f('ix_user_tenders_user_id'), table_name='user_tenders')
    op.drop_index(op.f('ix_user_tenders_tender_id'), table_name='user_tenders')
    op.drop_table('user_tenders')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('tender_types')
    op.drop_index(op.f('ix_tender_summaries_tender_uri'), table_name='tender_summaries')
    op.drop_table('tender_summaries')
    op.drop_table('keywords')
    op.drop_table('cpv_codes')
    # ### end Alembic commands ###
