"""TenderSummary changed to TenderDocuments

Revision ID: f7f0014dfddc
Revises: 4b2af185d819
Create Date: 2025-03-22 19:13:28.436604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f0014dfddc'
down_revision: Union[str, None] = '4b2af185d819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_documents',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('tender_uri', sa.String(length=1024), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url_document', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_documents_tender_uri'), 'tender_documents', ['tender_uri'], unique=True)
    op.drop_table('tender_summaries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_summaries',
    sa.Column('id', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('tender_uri', sa.VARCHAR(length=1024, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('summary', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__tender_s__3213E83F1C5ED051')
    )
    op.drop_index(op.f('ix_tender_documents_tender_uri'), table_name='tender_documents')
    op.drop_table('tender_documents')
    # ### end Alembic commands ###
